spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://192.168.1.44:3306/sell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
    # 热部署生效
  devtools:
    restart:
      enabled: true
    #接口字段为空不传此字段
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
  port: 8081
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat
#  file: /var/log/tomcat/sell.log
#  level:
#    com.zyh.LogTest: debug
wechat:
  mpAppId: wx17641ae50a4fd095
  mpAppSecret: 181c62a4165c4ce4a734f94005ab7c7d
  openAppId:
  openAppSecret:
  mchId: 21
  mchKey: 3
  keyPath: sf

urlConfig:
  wechatMpAuthorize: http://zyhs.natapp1.cc/sell/wechat/UserInfo
  wechatOpenAuthorize: http://zyhs.natapp1.cc/sell/wechat/qrUserInfo
  projectUrl: